$script = <<SCRIPT
chmod 0600 /home/vagrant/.ssh/id_rsa
usermod -a -G vagrant ubuntu
cp -Rvf /home/vagrant/.ssh /home/ubuntu
chown -Rvf ubuntu /home/ubuntu
yum -y install epel-release 
yum -y update
yum -y install python-minimal python-apt ansible docker 
yum -y install screen curl wget sysstat tcpdump xmlstarlet jq
curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod 755 /usr/local/bin/docker-compose
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ansibleLabmaster1.box"
  #config.vm.box = "geerlingguy/centos7"
  config.vm.network "public_network"
  config.vm.synced_folder "./kube", "/kube"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end
end
